"""Dados mockados de agendamentos médicos usados pela API simulada."""

AGENDAMENTOS = [
    {
        "paciente": "Maria Oliveira Santos",
        "cpf": "123.456.789-00",
        "medico": "Dr. Carlos Andrade",
        "especialidade": "Cardiologia",
        "data": "2026-07-25",
        "horario": "09:00",
        "convenio": "Unimed",
        "status": "confirmado",
    },
    {
        "paciente": "João Pedro Lima",
        "cpf": "234.567.890-11",
        "medico": "Dra. Fernanda Costa",
        "especialidade": "Dermatologia",
        "data": "2026-07-25",
        "horario": "10:30",
        "convenio": "Bradesco Saúde",
        "status": "aguardando confirmação",
    },
    {
        "paciente": "Ana Beatriz Souza",
        "cpf": "345.678.901-22",
        "medico": "Dr. Ricardo Nunes",
        "especialidade": "Ortopedia",
        "data": "2026-07-26",
        "horario": "08:15",
        "convenio": "Particular",
        "status": "confirmado",
    },
    {
        "paciente": "Pedro Henrique Alves",
        "cpf": "456.789.012-33",
        "medico": "Dra. Juliana Ramos",
        "especialidade": "Clínico Geral",
        "data": "2026-07-26",
        "horario": "14:00",
        "convenio": "SulAmérica",
        "status": "cancelado",
    },
    {
        "paciente": "Camila Ferreira Dias",
        "cpf": "567.890.123-44",
        "medico": "Dr. Carlos Andrade",
        "especialidade": "Cardiologia",
        "data": "2026-07-27",
        "horario": "11:00",
        "convenio": "Unimed",
        "status": "confirmado",
    },
    {
        "paciente": "Lucas Gabriel Martins",
        "cpf": "678.901.234-55",
        "medico": "Dra. Fernanda Costa",
        "especialidade": "Dermatologia",
        "data": "2026-07-27",
        "horario": "16:30",
        "convenio": "Amil",
        "status": "aguardando confirmação",
    },
    {
        "paciente": "Beatriz Cardoso Rocha",
        "cpf": "789.012.345-66",
        "medico": "Dr. Ricardo Nunes",
        "especialidade": "Ortopedia",
        "data": "2026-07-28",
        "horario": "09:45",
        "convenio": "Particular",
        "status": "confirmado",
    },
    {
        "paciente": "Gustavo Henrique Pires",
        "cpf": "890.123.456-77",
        "medico": "Dra. Juliana Ramos",
        "especialidade": "Clínico Geral",
        "data": "2026-07-28",
        "horario": "17:15",
        "convenio": "Bradesco Saúde",
        "status": "confirmado",
    },
]
